apiVersion: v1
kind: Service
metadata:
  name: warehouse-management-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30006
  selector:
    app: warehouse-management
