apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-management-deployment
spec:
  template:
    metadata:
      labels:
        app: warehouse-management
    spec:
      containers:
        - name: warehouse-management
          image: warehouse-management:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

  replicas: 1
  selector:
    matchLabels:
      app: warehouse-management
